### ISSUE TITLE
[Mirishita Inst] When backing from another page, the volume setting is not respected 

### ISSUE THREAD

**Issue by fireattack** [KinoMyu/kinomyu.github.io#1]
STR (tested with Chrome):

1. Open https://kinomyu.github.io/music/inst/ and adjust volume to low, then play.
2. Go to another website within the same tab by any means. 
3. Back (alt+←), notice the volume slider still remembers your setting (low).
4. Play again. However, the volume is actually full.

Not really a big issue, just in case you want to be perfect.

**Comment by KinoMyu** [comment]
This issue seems to appear on all browsers besides Firefox (my test browser). It should be fixed now that audio volume is set according to the slider upon loading the page. Thanks for catching this!
